# Generated by Django 4.2.1 on 2023-05-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='Priority',
        ),
    ]
